### PR TITLE
Integration specs for views and fix n+1 problems

### PR DESCRIPTION
**Pull request by danielochuba**
# Hello Reviewer, I have no coding partner for the week.
Screenshot 2023-08-29 002239

Before fix
image
image

after fix
image
image

# Blog app - integration specs for views and fix n+1 problems
### In this pull request I added integration tests for user interactions through the following:
- Installed `Capybara` 
- Used `Capybara` to write integration tests for each view

### CODE REVIEW

**Comment by topeogunleye** [comment]
@danielochuba why are there no commits from your coding partner?

**Comment by topeogunleye** [comment]
Hi @danielochuba, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ⚠️

   - You have submitted a pair programming project with no contributions from your partner.  Kindly report any issue you had with your partner to the `student success` team and they'll permit you to work solo or look for a suitable partner. Attach a screenshot of the message you received from `student success` stating that you can do the project alone in the pull request description and resubmit this PR👍

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

>Invalid Code Review Request **does not count** into the code reviews limit.

**Comment by danielochuba** [comment]
@topeogunleye please Did you read the pull request description?

**Review by Reem-lab — APPROVED** [review]
# Hi @danielochuba,  👋🏻👋🏻

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


## Highlights

- [ ]  Followed Gitflow 💯
- [ ]  Descriptive PR⭐
- [ ]  Kudos for working on the Tests🤩
- [ ]  No Linters error ✅
- [ ] All tests passed 🙏🏻
- [ ] N+1 problem solved ✅




## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by topeogunleye** [comment]
> @topeogunleye please Did you read the pull request description?

Hi @danielochuba, Please be informed that what you put there wasn't there before I made my comment and you edited the pull request?

**Comment by danielochuba** [comment]
> > @topeogunleye please Did you read the pull request description?
> 
> Hi @danielochuba, Please be informed that what you put there wasn't there before I made my comment and you edited the pull request?

ohh, so sorry, I initially included it , it looks like it was from my end

**Pull request merged**
